### GENERAL SETTINGS ###

# Site settings
title: M A S K
description: "MASK is a collection of virtual reality wearables that help overcoming difficulties. Here you can find all the resource to create your own MASK and World."
analytics: UA-47735603-8
baseurl: "/MASK" #important: start with /
url: "http://www.jhclaura.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#fef28e" #"#F70031" 
  primary_rgb: "254,242,142" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#24b572" #"36, 181, 114"
  link: "#da4571"
  link_hover: "#4ab6a7"
  footer_heading: "#ffffff"
  footer_content: "#84f2e3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  # - title: dribbble
  #   url:
  # - title: facebook
  #   url:
  - title: twitter
    url: http://twitter.com/jhclaura
  - title: instagram
    url: http://instagram.com/jhclaura
  - title: tumblr
    url: http://lauracollection.tumblr.com/
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 10003, New York,
    - United States.
email: jhclaura@gmail.com
tel: +1 626-905-9397


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
# members:
#   - name: Laura Chen
#     position: Lead
#     text: Let's use mask to change the world!
#     img: me.jpg
#     social:
#       - title: envelope #use for email address
#         url: mailto:jhclaura@gmail.com
#       - title: twitter
#         url: http://twitter.com/jhclaura
#   - name: Paul Jameson
#     position: Lead Designer
#     text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#     img: team02.jpg
#     social:
#       - title: envelope #use for email address
#         url: mailto:name@domain.com
#       - title: twitter
#         url: http://twitter.com/handle
#   - name: Laura Sommers
#     position: Lead Developer
#     text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#     img: team03.jpg
#     social:
#       - title: envelope #use for email address
#         url: mailto:name@domain.com
#       - title: twitter
#         url: http://twitter.com/handle
#   - name: Martin Blunt
#     position: Marketing
#     text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#     img: team04.jpg
#     social:
#       - title: envelope #use for email address
#         url: mailto:name@domain.com
#       - title: twitter
#         url: http://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
# clients:
#   - name: dribbble
#     img: client01.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "MASK - We are who we pretend to be."

# Testimonial content. Shown on Home and About page. 
# testimonial:
#     message: "..."
#     author: ...
#     position: ...