### GENERAL SETTINGS ###

# Site settings
title: MASK
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/https://github.com/jhclaura/MASK" #important: start with /
url: "http://www.jhclaura.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#fef28e" #"#F70031" 
  primary_rgb: "254,242,142" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#24b572" #"#33004D"
  link: "#92c1bb"
  link_hover: "#66c1b5"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url: 
  - title: instagram
    url: 
  - title: tumblr
    url: 
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 10003, New York,
    - United States.
email: jhclaura@gmail.com
tel: +1 626-905-9397


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Laura Chen
    position: CEO
    text: Hello!
    img: me.jpg
    social:
      - title: envelope #use for email address
        url: mailto:jhclaura@gmail.com
      - title: twitter
        url: http://twitter.com/jhclaura
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Laura Sommers
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Laura Chen is Laura Chen."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "..."
    author: ...
    position: ...